language: php

php:
  - 5.6
  - 7.0

addons:
  ssh_known_hosts:
    - imc.clowting.me
    - 178.62.253.16

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

deploy:
  - provider: script
    script: .travis/deploy-staging.sh
    on:
      branch: develop
      php: 7.0
  - provider: script
    script: .travis/deploy-production.sh
    on:
      branch: master
      php: 7.0